id = "form"
name = "FORM"
version = "0.0.1"
schema_version = 1
authors = ["Simone"]
description = "FORM language support for Zed"
repository = "https://github.com/simonecaletti/zed-form-extension"

[grammars.form]
repository = "https://github.com/simonecaletti/tree-sitter-form"
rev = "f47845a146ef17cffeaf5527c3fd98c1d60790dc"
